---
title: "NIBRS-crime-report"
output: html_document
params:
  year: 2022
  yearPY: 2021
  month: March
  month1: Mar
  month2: Apr

---
#IMPORTANT
Make sure to update line 223 before running this .Rmd. Refer to the `How-To-Instructions.Rmd` for more information.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load Dependencies
```{r}
library(dplyr)        #tools for cleaning data
library(flextable)    #flextable output
library(officer)      #tools for powerpoint output
library(data.table)   #transposing data
library(here)         #file path management
library(janitor)      #adorn totals
library(customLayout) #powerpoint formatting
library(grid)         #inset map
library(ggplot2)      #data visualization
library(docxtractr)   #convert pptx to pdf
library(scales)       #functions for visualization

#spatial packages
library(sf)           #tools for manipulating spatial data
library(gateway)      #load stl spatial data
library(tmap)         #mapping tools

#load crime data
load(file = here::here("NIBRS", "data", params$year, params$month1, "clean-crime-data.rda"))
#Check to only have current and previous months shown
if(grepl(params$month1, params$month)){
base <- dplyr::select(base, -grep(params$month2, colnames(base)))
}
if(grepl(params$month1, params$month)){
basePY <- dplyr::select(basePY, -grep(params$month2, colnames(basePY)))
}
#load spatial data
bound <- gw_get_data("Neighborhoods", "sf")
st_read(here::here("NIBRS", "data", "stlstreets", "tgr_str_cl.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = st_crs(bound)) -> streets
#load pptx template
report <- read_pptx(here::here("NIBRS", "data", "template.pptx"))
```

#Create Appropriate Folders
```{r}
here::here()
dir.create(getwd())
dir.create(here::here(file.path("NIBRS", "results", params$year)))
dir.create(here::here(file.path("NIBRS", "results", params$year, params$month)))
dir.create(here::here(file.path("NIBRS", "results", "presentations", params$year)))
dir.create(here::here(file.path("NIBRS", "results", "presentations", params$year, params$month)))
```

```{r}
# summary note colors
reg20 <- fp_text(color = 'black', font.size = 20)
reg16 <- fp_text(color = 'black', font.size = 16)
bold <- fp_text(color = "black", font.size = 20, bold = TRUE)
boldline <- fp_text(color = "black", font.size = 28, bold = TRUE, underlined = TRUE)
# for loop objects
type <- c("Property", "Society", "Person", "Unspecified")
#create neighborhood object
neighborhood <- c(39,38,28)
```

```{r officer layout}
#create custom powerpoint layout
lay <- lay_new(matrix(1:4, nc = 2), widths = c(2,2), heights = c(.75,2.25))
title <- lay_new(1, widths = 2, heights = 2)
layout <- lay_bind_row(title, lay, heights = c(1,6))
lay_show(layout)

offlayout <- phl_layout(layout,
    margins = c(0.25, 0.25, 0.25, 0.25),
    innerMargins = rep(0.15,4))

lay1 <- lay_new(matrix(1:4, nc = 2), widths = c(2,2), heights = c(.5,2.5))
layout1 <- lay_bind_row(title, lay1, heights = c(1,6))
lay_show(layout1)

offlayout01 <- phl_layout(layout1,
    margins = c(0.25, 0.25, 0.25, 0.25),
    innerMargins = rep(0.15,4))

#spatial reference layout
lay2 <- lay_new(matrix(1:4, nc = 2), widths = c(1,3), heights = c(.5,2.5))
layout2 <- lay_bind_row(title, lay2, heights = c(1,6))
lay_show(layout2)

offlayout02 <- phl_layout(layout2,
    margins = c(0.25, 0.25, 0.25, 0.25),
    innerMargins = rep(0.15,4))

#previous year comparison layout
lay3 <- lay_new(matrix(1:2))
layout3 <- lay_bind_row(title, lay3, heights = c(1,6))
lay_show(layout3)

offlayout03 <- phl_layout(layout3,
    margins = c(0.25, 0.25, 0.25, 0.25),
    innerMargins = rep(0.15,4))
```

```{r powerpoint title}
#title slide
  add_slide(report, layout = "Title Slide", master = "Facet")%>%
  ph_with(value = "Forest Park Southeast, Central West End, Botanical Heights,", location = ph_location_type(type = "ctrTitle"))%>%
  ph_with(c(paste("Monthly Crime Report:", params$month, params$year, sep = " "), "Washington University Medical Center"), location = ph_location_type(type = "subTitle")) -> report

#history of crime reporting slide
  add_slide(report, layout = "Title and Content", master = "Facet")%>%
  ph_with(value = c("Since the 1929 the Uniform Crime Report (UCR) has used a Summary Reporting System (SRS) to collect monthly counts of the number of crimes", "In 1982 the Bureau of Justice Statistics and the FBI sponsored a study with the objective of revising the existing form of reporting crime. Through this, the National Incident Based Reporting System (NIBRS) was created", "The FBI UCR Program transitioned to a NIBRS only data collection by January 1, 2021. Other states have followed suit and SLMPD has been working to make this same transition"), location = ph_location_type(type = "body"))%>%
    ph_with("History of Crime Reporting", location = ph_location_type(type="title"))-> report

#NIBRS vs SRS
  add_slide(report, layout = "Title and Content", master = "Facet")%>%
  ph_with(value = c("NIBRS captures details on each single crime incident—as well as on separate offenses within the same incident—including information on victims, known offenders, relationships between victims and offenders, arrestees, and property involved in crimes", "Standardizes crime reporting across all local, state, and tribal law enforcement agencies", "SRS only counted the most serious offense (i.e. if a murder and robbery occurred, only the murder is counted) while NIBRS counts up to 10 crimes per incident", "Current NIBRS reporting are not directly comparable to the previous UCR “hierarchy” numbers. With this change, you will likely see increases in crime statistics. This increase does not mean that crime is necessarily increasing, but rather that crime is being reported in a non-hierarchical format, with more detail and counting each individual crime"), location = ph_location_type(type = "body"))%>%
    ph_with("NIBRS vs SRS", location = ph_location_type(type="title"))-> report

#NIBRS and SLMPD
  add_slide(report, layout = "Title and Content", master = "Facet")%>%
  ph_with(value = c("Unforeseen technology delays and the incompatibility in comparing crime (NIRBS V. UCR) has caused delays in making the crime information available", "The City of St Louis Information Technology Division (I.T.) has created a series of internal 2021 NIBRS reports", "Because of this transition information is limited to counts of each crime by neighborhood"), location = ph_location_type(type = "body"))%>%
    ph_with("NIBRS and SLMPD", location = ph_location_type(type="title"))-> report

#add core neighborhood slide
report%>%
  add_slide(layout = "Title Slide", master = "Facet")%>%
  ph_with(value = "Core Neighborhoods", location = ph_location_type(type = "ctrTitle"))  -> report
```

```{r}
bb <- st_bbox(bound %>% filter(NHD_NUM %in% neighborhood))
str_crop <- st_crop(streets, bb)
for (i in neighborhood) {
  #create neighborhood data
  temp_df <- filter(base, nbhd_num == i)
  temp_df_PY <- filter(basePY, nbhd_num == i)
  nbhd <- unique(temp_df$nbhd_name)

bound%>%
tm_shape(bbox = bb) +
  tm_fill(col = "grey") +
  tm_polygons()+
  bound%>%
  filter(., NHD_NUM == i)%>%
  tm_shape()+
  tm_fill(col = "mistyrose",
          alpha = .5)+
  tm_borders(col = "black",
             lwd = 2)+
  str_crop%>%
  tm_shape()+
  tm_lines(col = "white",
           lwd = .5,
           alpha = .5)+
  bound%>%
  tm_shape(bbox = bb) +
  tm_fill(col = "grey",
          alpha = 0,
          lwd = 1) +
  tm_polygons()+
  tm_credits("Source: City of St. Louis", position = c("left", "BOTTOM"), size = .5)+
  tm_layout(frame = FALSE) -> map

bound%>%
tm_shape()+
  tm_fill(col = "grey")+
  tm_borders(col = "white")+
  bound%>%
  filter(., NHD_NUM == i)%>%
  tm_shape()+
  tm_fill(col = "mistyrose")+
  tm_borders(col = "black")-> inset

tmap_save(map, insets_tm = inset, insets_vp = viewport(0.8, 0.75, width = 0.4, height = 0.4), file = here::here("NIBRS", "data", "neighborhoods", paste(nbhd, ".jpeg", sep = "")), width = 9, height = 5, units = "in")

#create formatted title
nbhd_title <- block_list(fpar(ftext(nbhd), fp_p = fp_par(text.align = "center")))
#create powerpoint slide
add_slide(report, layout = "Title and Content", master = "Facet")%>%
  ph_with(external_img(here::here("NIBRS", "data", "neighborhoods", paste(nbhd, ".jpeg", sep = "")), height = 5, width = 9), location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with(nbhd_title, location = ph_location_type(type = "title")) -> report

# create summary notes - month comparison code
#reference column name using params$month1
tc <- sum(temp_df[grep(params$month1, colnames(temp_df))])
persons <- filter(temp_df, type == "Person")
persons <- sum(persons[grep(params$month1, colnames(temp_df))])
society <- filter(temp_df, type == "Society")
society <- sum(society[grep(params$month1, colnames(temp_df))])
property <- filter(temp_df, type == "Property")
property <- sum(property[grep(params$month1, colnames(temp_df))])
unspec <- filter(temp_df, type == "Unspecified")
unspec <- sum(unspec[grep(params$month1, colnames(temp_df))])

tc_PY <- sum(temp_df_PY[grep(params$month1, colnames(temp_df_PY))])
persons_PY <- filter(temp_df_PY, type == "Person")
persons_PY <- sum(persons_PY[grep(params$month1, colnames(temp_df_PY))])
society_PY <- filter(temp_df_PY, type == "Society")
society_PY <- sum(society_PY[grep(params$month1, colnames(temp_df_PY))])
property_PY <- filter(temp_df_PY, type == "Property")
property_PY <- sum(property_PY[grep(params$month1, colnames(temp_df_PY))])
unspec_PY <- filter(temp_df_PY, type == "Unspecified")
unspec_PY <- sum(unspec_PY[grep(params$month1, colnames(temp_df_PY))])

pct_chg_mth1 <- (tc - tc_PY)/tc_PY
pct_chg_mth <- percent(pct_chg_mth1)
if(is.nan(pct_chg_mth1)){pct_chg_mth[is.nan(pct_chg_mth1)] <- 0}
if(is.infinite(pct_chg_mth1)){pct_chg_mth[is.infinite(pct_chg_mth1)] <- "Infinite"}

pct_chg_persons1 <- (persons - persons_PY)/persons_PY
pct_chg_persons <- percent(pct_chg_persons1)
if(is.nan(pct_chg_persons1)){pct_chg_persons[is.nan(pct_chg_persons1)] <- 0}
if(is.infinite(pct_chg_persons1)){pct_chg_persons[is.infinite(pct_chg_persons1)] <- "Infinite"}

pct_chg_society1 <- (society - society_PY)/society_PY
pct_chg_society <- percent(pct_chg_society1)
if(is.nan(pct_chg_society1)){pct_chg_society[is.nan(pct_chg_society1)] <- 0}
if(is.infinite(pct_chg_society1)){pct_chg_society[is.infinite(pct_chg_society1)] <- "Infinite"}

pct_chg_property1 <- (property - property_PY)/property_PY
pct_chg_property <- percent(pct_chg_property1)
if(is.nan(pct_chg_property1)){pct_chg_property[is.nan(pct_chg_property1)] <- 0}
if(is.infinite(pct_chg_property1)){pct_chg_property[is.infinite(pct_chg_property1)] <- "Infinite"}

pct_chg_unspec1 <- (unspec - unspec_PY)/unspec_PY
pct_chg_unspec <- percent(pct_chg_unspec1)
if(is.nan(pct_chg_unspec1)){pct_chg_unspec[is.nan(pct_chg_unspec1)] <- 0}
if(is.infinite(pct_chg_unspec1)){pct_chg_unspec[is.infinite(pct_chg_unspec1)] <- "Infinite"}

sprint_1 <- sprintf("%s total crimes in %s %s",
                    tc, params$month, params$year)

# text formatting
color20a <- fp_text(color = ifelse(pct_chg_mth1 == 0, "#00B0F0", ifelse(pct_chg_mth < 0, "#00B050", "red")), font.size = 20)
color16a <- fp_text(color = ifelse(pct_chg_persons1 == 0, "#00B0F0", ifelse(pct_chg_persons < 0, "#00B050", "red")), font.size = 16)
color16b <- fp_text(color = ifelse(pct_chg_society1 == 0, "#00B0F0", ifelse(pct_chg_society < 0, "#00B050", "red")), font.size = 16)
color16c <- fp_text(color = ifelse(pct_chg_property1 == 0, "#00B0F0", ifelse(pct_chg_property < 0, "#00B050", "red")), font.size = 16)
color16d <- fp_text(color = ifelse(pct_chg_unspec1 == 0, "#00B0F0", ifelse(pct_chg_unspec < 0, "#00B050", "red")), font.size = 16)

# create summary notes - month comparison
summary <- block_list(
  fpar(ftext(sprint_1, boldline)),
  fpar(ftext(paste(" ", sep = ""), reg20),
      ftext(paste(pct_chg_mth, "change ", sep = " "), color20a),
      ftext(paste("compared to ", params$month, " ", (params$year - 1),
            " (", tc_PY, " total crimes)", sep = ""), reg20)),
  fpar(ftext(paste(persons, "crime(s) against persons", sep = " "), bold),
      ftext(paste(" in", params$month, params$year, sep = " "), reg20)),
  fpar(ftext(paste(" ", sep = ""), reg16),
      ftext(paste(pct_chg_persons, "change", sep = " "), color16a),
      ftext(paste(" compared to ", params$month, " ", (params$year - 1), " (", persons_PY, " crimes against persons)", sep = ""), reg16)),
  fpar(ftext(paste(society, "crime(s) against society", sep = " "), bold),
      ftext(paste(" in", params$month, params$year, sep = " "), reg20)),
  fpar(ftext(paste(" ", sep = ""), reg16),
      ftext(paste(pct_chg_society, "change", sep = " "), color16b),
      ftext(paste(" compared to ", params$month, " ", (params$year - 1), " (", society_PY, " crimes against society)", sep = ""), reg16)),
  fpar(ftext(paste(property, "crime(s) against propety", sep = " "), bold),
      ftext(paste(" in", params$month, params$year, sep = " "), reg20)),
  fpar(ftext(paste(" ", sep = ""), reg16),
      ftext(paste(pct_chg_property, "change", sep = " "), color16c),
      ftext(paste(" compared to ", params$month, " ", (params$year - 1), " (", property_PY, " crimes against property)", sep = ""), reg16)),
  fpar(ftext(paste(unspec, "unspecified crime(s)", sep = " "), bold),
      ftext(paste(" in", params$month, params$year, sep = " "), reg20)),
  fpar(ftext(paste(" ", sep = ""), reg16),
      ftext(paste(pct_chg_unspec, "change", sep = " "), color16d),
      ftext(paste(" compared to ", params$month, " ", (params$year - 1), " (", unspec_PY, " unspecified crimes)", sep = ""), reg16))
  )

# write summary notes to powerpoint slide
# create formatted title
title <- block_list(fpar(ftext(paste(nbhd, ": Month Summary Notes", sep = "")), fp_p = fp_par(text.align = "center")))

  add_slide(report, layout = 'Title and Content', master = 'Facet')%>%
  ph_with(title, location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE,
          level_list = c(1, 1, 2, 3, 2, 3, 2, 3, 2,3 )) -> report

# create summary notes - year to date comparison code
#reference columns
tc_ytd <- sum(temp_df[c(5:7)])
persons_ytd <- filter(temp_df, type == "Person")
persons_ytd <- sum(persons_ytd[c(5:7)])
society_ytd <- filter(temp_df, type == "Society")
society_ytd <- sum(society_ytd[c(5:7)])
property_ytd <- filter(temp_df, type == "Property")
property_ytd <- sum(property_ytd[c(5:7)])
unspec_ytd <- filter(temp_df, type == "Unspecified")
unspec_ytd <- sum(unspec_ytd[c(5:7)])

tc_ytd_PY <- sum(temp_df_PY[c(5:7)])
persons_ytd_PY<- filter(temp_df_PY, type == "Person")
persons_ytd_PY <- sum(persons_ytd_PY[c(5:7)])
society_ytd_PY <- filter(temp_df_PY, type == "Society")
society_ytd_PY <- sum(society_ytd_PY[c(5:7)])
property_ytd_PY <- filter(temp_df_PY, type == "Property")
property_ytd_PY <- sum(property_ytd_PY[c(5:7)])
unspec_ytd_PY <- filter(temp_df_PY, type == "Unspecified")
unspec_ytd_PY <- sum(unspec_ytd_PY[c(5:7)])

pct_chg_ytd1 <- (tc_ytd - tc_ytd_PY)/tc_ytd_PY
pct_chg_ytd <- percent(pct_chg_ytd1)
if(is.nan(pct_chg_ytd1)){pct_chg_ytd[is.nan(pct_chg_ytd1)] <- 0}
if(is.infinite(pct_chg_ytd1)){pct_chg_ytd[is.infinite(pct_chg_ytd1)] <- "Infinite"}

pct_chg_persons1 <- (persons_ytd - persons_ytd_PY)/persons_ytd_PY
pct_chg_persons <- percent(pct_chg_persons1)
if(is.nan(pct_chg_persons1)){pct_chg_persons[is.nan(pct_chg_persons1)] <- 0}
if(is.infinite(pct_chg_persons1)){pct_chg_persons[is.infinite(pct_chg_persons1)] <- "Infinite"}

pct_chg_society1 <- (society_ytd - society_ytd_PY)/society_ytd_PY
pct_chg_society <- percent(pct_chg_society1)
if(is.nan(pct_chg_society1)){pct_chg_society[is.nan(pct_chg_society1)] <- 0}
if(is.infinite(pct_chg_society1)){pct_chg_society[is.infinite(pct_chg_society1)] <- "Infinite"}

pct_chg_property1 <- (property_ytd - property_ytd_PY)/property_ytd_PY
pct_chg_property <- percent(pct_chg_property1)
if(is.nan(pct_chg_property1)){pct_chg_property[is.nan(pct_chg_property1)] <- 0}
if(is.infinite(pct_chg_property1)){pct_chg_property[is.infinite(pct_chg_property1)] <- "Infinite"}

pct_chg_unspec1 <- (unspec_ytd - unspec_ytd_PY)/unspec_ytd_PY
pct_chg_unspec <- percent(pct_chg_unspec1)
if(is.nan(pct_chg_unspec1)){pct_chg_unspec[is.nan(pct_chg_unspec1)] <- 0}
if(is.infinite(pct_chg_unspec1)){pct_chg_unspec[is.infinite(pct_chg_unspec1)] <- "Infinite"}

sprint_2 <- sprintf("%s total crimes in %s",
tc_ytd, params$year)

# text formatting
color20a <- fp_text(color = ifelse(pct_chg_ytd1 == 0, "#00B0F0", ifelse(pct_chg_ytd < 0, "#00B050", "red")), font.size = 20)
color16a <- fp_text(color = ifelse(pct_chg_persons1 == 0, "#00B0F0", ifelse(pct_chg_persons < 0, "#00B050", "red")), font.size = 16)
color16b <- fp_text(color = ifelse(pct_chg_society1 == 0, "#00B0F0", ifelse(pct_chg_society < 0, "#00B050", "red")), font.size = 16)
color16c <- fp_text(color = ifelse(pct_chg_property1 == 0, "#00B0F0", ifelse(pct_chg_property < 0, "#00B050", "red")), font.size = 16)
color16d <- fp_text(color = ifelse(pct_chg_unspec1 == 0, "#00B0F0", ifelse(pct_chg_unspec < 0, "#00B050", "red")), font.size = 16)

summary <- block_list(
  fpar(ftext(sprint_2, boldline)),
  fpar(ftext(paste(" ", sep = ""), reg20),
      ftext(paste(pct_chg_ytd, "change ", sep = " "), color20a),
      ftext(paste("compared to this time in ", (params$year - 1), " (", tc_ytd_PY, " total crimes)", sep = ""), reg20)),
  fpar(ftext(paste(persons_ytd, "crime(s) against persons", sep = " "), bold),
       ftext(paste(" in", params$year, sep = " "), reg20)),
  fpar(ftext(paste(" ", sep = ""), reg16),
       ftext(paste(pct_chg_persons, "change", sep = " "), color16a),
       ftext(paste(" compared to this time in ", (params$year - 1), " (", persons_ytd_PY, " crimes against persons)", sep = ""), reg16)),
  fpar(ftext(paste(society_ytd, "crime(s) against society", sep = " "), bold),
      ftext(paste(" in", params$year, sep = " "), reg20)),
  fpar(ftext(paste(" ", sep = ""), reg16),
      ftext(paste(pct_chg_society, "change", sep = " "), color16b),
      ftext(paste(" compared to this time in ", (params$year - 1), " (", society_ytd_PY, " crimes against society)", sep = ""), reg16)),
  fpar(ftext(paste(property_ytd, "crime(s) against property", sep = " "), bold),
       ftext(paste(" in", params$year, sep = " "), reg20)),
  fpar(ftext(paste(" ", sep = ""), reg16),
       ftext(paste(pct_chg_property, "change", sep = " "), color16c),
       ftext(paste(" compared to this time in ", (params$year - 1), " (", property_ytd_PY, " crimes against property)", sep = ""), reg16)),
  fpar(ftext(paste(unspec_ytd, "unspecified crime(s)", sep = " "), bold),
      ftext(paste(" in", params$year, sep = " "), reg20)),
  fpar(ftext(paste(" ", sep = ""), reg16),
      ftext(paste(pct_chg_unspec, "change", sep = " "), color16d),
      ftext(paste(" compared to this time in ", (params$year - 1), " (", persons_ytd_PY, " unspecified crimes)", sep = ""), reg16))
)

# write summary notes to powerpoint slide
# create formatted title
title <- block_list(fpar(ftext(paste(nbhd, ": Year to Date Summary Notes", sep = "")), fp_p = fp_par(text.align = "center")))

  add_slide(report, layout = 'Title and Content', master = 'Facet')%>%
  ph_with(title, location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE,
          level_list = c(1, 1, 2, 3, 2, 3, 2, 3, 2,3 )) -> report

###Current Year
###Must Change summarise every time you run code!
###
overview <- temp_df%>%
  dplyr::group_by(type)%>%
  dplyr::summarise(Jan = sum(Jan), Feb = sum(Feb), Mar = sum(Mar))%>%
  adorn_totals("row", name = "Total")%>%
  adorn_totals("col", name = "Total")%>%
  dplyr::rename("Type of Crime" = type)
###
###
###
#Make flextables from summary data
flextable(overview) %>%
  height_all(.25, part = "all")%>%
  add_header_lines(values = paste(params$year))%>%
  width(j = "Type of Crime", width = 1.5)-> flex

###Previous Year
###Must Change summarise every time you run code!
###
overviewPY <- temp_df_PY %>%
  dplyr::group_by(type)%>%
  dplyr::summarise(Jan = sum(Jan), Feb = sum(Feb), Mar = sum(Mar))%>%
  adorn_totals("row", name = "Total")%>%
  adorn_totals("col", name = "Total")%>%
  dplyr::rename("Type of Crime" = type)
###
###
###
#Make flextables from summary data
flextable(overviewPY) %>%
  height_all(.25, part = "all")%>%
  add_header_lines(values = paste(params$yearPY))%>%
  width(j = "Type of Crime", width = 1.5)-> flex01

add_slide(report, layout = "Title and Content", master = "Facet")%>%
  phl_with_flextable(olay = offlayout03, id = 2, flex)%>%
  phl_with_flextable(olay = offlayout03, id = 3, flex01)%>%
  ph_with(nbhd_title,
               location = ph_location_type(
                 type = "title") )-> report

# A function factory for getting integer y-axis values.
integer_breaks <- function(n = 5, ...) {
    fxn <- function(x) {
        breaks <- floor(pretty(x, n, ...))
        names(breaks) <- attr(breaks, "labels")
        breaks
    }
    return(fxn)
}

#Month by Month total crime plot
plot_df <- temp_df%>%
  summarise(Jan = sum(Jan), Feb = sum(Feb), Mar = sum(Mar))
#reshape data
plot_df <- reshape2::melt(plot_df)

ggplot(plot_df, aes(x=variable, y=value, group = 1)) +
    geom_line(color="blue") +
    geom_point() +
    xlab("Month") + ylab("Total Crimes")+
    scale_y_continuous(breaks = integer_breaks())

ggsave(here::here("NIBRS", "results",  params$year, params$month, paste(nbhd, "_graph.jpeg", sep = "")), width = 9, height = 5, units = "in")

add_slide(report, layout = "Title and Content", master = "Facet")%>%
  ph_with(external_img(here::here("NIBRS", "results", params$year, params$month, paste(nbhd, "_graph.jpeg", sep = "")), width = 9, height = 5), location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with(nbhd_title,
               location = ph_location_type(
                 type = "title") )-> report

for (x in type) {
  #create formatted title
title <- block_list(fpar(ftext(paste(nbhd, ": ", x, " Crimes", sep = "")), fp_p = fp_par(text.align = "center")))

  sub <- temp_df%>%
    filter(type == x)%>%
    subset(select=-c(nbhd_num,nbhd_name,type))%>%
    adorn_totals(., "col", name = "Total")

  if(x != "Property"){
    sub <- adorn_totals(sub, "row", name = "Total")
    head <- head(sub, 21)
  }else{
    head <- head(sub, 19)
  }

 flextable(head)%>%
  height_all(.25, part = "all")%>%
  width(width = 3, j = "Crime")->ft

if(x == "Unspecified"){
  #use offlayout for all unspecified flextables
  add_slide(report, layout = "Title and Content", master = "Facet")%>%
  phl_with_flextable(olay = offlayout, id = 3, ft)%>%
  ph_with(title,
               location = ph_location_type(
                 type = "title") ) -> report
}else{
  add_slide(report, layout = "Title and Content", master = "Facet")%>%
  phl_with_flextable(olay = offlayout01, 2, ft)%>%
  #ph_with(ft, location = ph_location_type(type = "body"), use_loc_size = TRUE)%>%
  ph_with(title,
               location = ph_location_type(
                 type = "title") ) -> report
}

if(x == "Property"){
  #add row totals from ft & ft2
  tail <- adorn_totals(sub, "row", name = "Total")
  #select observations after first 20
  tail <- tail(tail, -19)
  flextable(tail)%>%
    height_all(.25, part = "all")%>%
    width(width = 3, j = "Crime") -> ft2

#add to powerpoint report
  add_slide(report, layout = "Title and Content", master = "Facet")%>%
  phl_with_flextable(olay = offlayout01, 3, ft2)%>%
  ph_with(title,
               location = ph_location_type(
                 type = "title") ) -> report
}
}
if(i == 38){
#add core neighborhood slide
report%>%
  add_slide(layout = "Title Slide", master = "Facet")%>%
  ph_with(value = "Neighboring Geographies", location = ph_location_type(type = "ctrTitle"))  -> report
}
}
#Remove blank template slide
remove_slide(report, index = 1)
#save output
#print(report, target = here::here("NIBRS", "results", "test.pptx"))
```

```{r}
# save powerpoint report
print(report, target = here::here("NIBRS", "results", "presentations", params$year, params$month, paste("fpse-bot-cwe-mc-", params$month, params$year, ".pptx", sep = "")))

#delete any existing fpse-bot-cwe-mc file in the Shiny app
#shinydr <- "/Users/loganbogenut/Documents/GitHub/crime_interactive/crime_interactive/www/"
#file.remove(file.path(shinydr, dir(path = shinydr, pattern = "Center_crime")))

#convert & save powerpoint as PDF to Shiny app
#convert_to_pdf(path = here::here("NIBRS", "results", "presentations", params$year, params$month, paste("fpse-bot-cwe-mc-", params$month, params$year, ".pptx", sep = "")),
               #pdf_file = sub("[.]pptx", ".pdf", paste("~/Documents/GitHub/crime_interactive/crime_interactive/www/", "Forest Park Southeast, Botanical Heights, Central West End, Medical Center_crime", ".pptx", sep = "")))

#Create PDF to be stored in current wd
mydir <- paste("/Users/jesstevens/Documents/Github/WUMCRC/Projects/monthly-crime-reports/NIBRS/results/presentations/", params$year, "/", params$month, "/", sep = "")
file.remove(file.path(mydir, dir(path = mydir, pattern = paste("fpse-bot-cwe-mc-", params$month, params$year, ".pdf", sep=""))))

#convert & save powerpoint as PDF to presentations subfolder
convert_to_pdf(path = here::here("NIBRS", "results", "presentations", params$year, params$month, paste("fpse-bot-cwe-mc-", params$month, params$year, ".pptx", sep = "")),
               pdf_file = sub("[.]pptx", ".pdf", paste(mydir, "fpse-bot-cwe-mc-", params$month, params$year, ".pptx", sep = "")))
```


###Inset Map
```{r, eval = FALSE}
library(sf)
library(gateway)


nbhds <- sort(unique(data_sf$nbhd_name))
for (i in neighborhood) {

  #new tmap with bbox
bound%>%
tm_shape(bbox = bb) +
  tm_fill(col = "grey") +
  tm_polygons()+
  bound%>%
  filter(., NHD_NUM == i)%>%
  tm_shape()+
  tm_fill(col = "forestgreen")+
  tm_credits("Source: City of St. Louis", position = c("left", "BOTTOM"), size = .5)+
  tm_layout(frame = FALSE)-> map



bound%>%
tm_shape()+
  tm_fill(col = "grey")+
  tm_borders(col = "white")+
  bound%>%
  filter(., NHD_NUM == i)%>%
  tm_shape()+
  tm_fill(col = "forestgreen")+
  tm_borders(col = "white")-> inset

tmap_save(map, insets_tm = inset, insets_vp = viewport(0.8, 0.75, width = 0.4, height = 0.4), file = here::here("NIBRS", "data", params$year, "test.jpeg"), width = 9, height = 5, units = "in")

}
```
