---
title: "NIBRS-crime-report"
output: html_document
params:
  year: 2021
  month: March
  month1: Mar
  month2: Apr
  #Num referes to the column of the current month. Because months come in pairs in this dataset, if the month is first (i.e. January in Jan-Feb, or March in Mar-Apr) then the num should be set to 2. If it comes second (i.e. Feb in Jan-Feb, or Apr in Mar-Apr) then num should be set to 3.
  num: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load Dependencies
```{r}
library(dplyr)        #tools for cleaning data
library(flextable)    #flextable output
library(officer)      #tools for powerpoint output
library(data.table)   #transposing data
library(here)         #file path management
library(janitor)      #adorn totals
library(customLayout) #powerpoint formatting
library(grid)       #inset map
library(sf)
#load crime data
load(file = here::here("NIBRS", "data", params$year, paste(params$month1, "-", params$month2, sep = ""), "clean-crime-data.rda"))
#Check to only have current and previous months shown
if(grepl(params$month1, params$month)){
base <- select(base, -grep(params$month2, colnames(base)))
tot <- select(tot, -grep(params$month2, colnames(tot)))
}
#load spatial data
bound <- gw_get_data("Neighborhoods", "sf")
# create powerpoint
report <- read_pptx()
```


```{r}
# summary note colors
reg24 <- fp_text(color = 'black', font.size = 24)
bold <- fp_text(color = "black", font.size = 24, bold = TRUE)
boldline <- fp_text(color = "black", font.size = 28, bold = TRUE, underlined = TRUE)
# for loop objects
type <- c("Property", "Society", "Person", "Unspecified")
#create neighborhood object
neighborhood <- c(28,38,39)
```

```{r officer layout}
#create custom powerpoint layout
 lay  <- lay_new(
  matrix(1:4, nc = 2),
  widths = c(3, 2),
  heights = c(1, 2))
title <- lay_new(1, widths = 2, heights = 3)
layout <- lay_bind_row(title, lay, heights = c(1,6))
lay_show(layout)
offlayout <- phl_layout(layout,
    margins = c(0.25, 0.25, 0.25, 0.25),
    innerMargins = rep(0.15,4))

lay1 <- lay_new(matrix(1:4, nc = 2), widths = c(2,2), heights = c(2,1)) 
title1 <- lay_new(1, widths = 2, heights = 2)
layout1 <- lay_bind_row(title1, lay1, heights = c(1,6))
lay_show(layout1)

offlayout01 <- phl_layout(layout1,
    margins = c(0.25, 0.25, 0.25, 0.25),
    innerMargins = rep(0.15,4))
```

```{r powerpoint title}
#title slide
report%>%
  add_slide(layout = "Title Slide", master = "Office Theme")%>%
  ph_with(value = "Forest Park Southeast, Botanical Heights, Central West End", location = ph_location_type(type = "ctrTitle"))%>%
  ph_with(c(paste("Monthly Crime Report:", params$month, params$year, sep = " "), "Washington University Medical Center"), location = ph_location_type(type = "subTitle")) -> report
```

```{r}
bb <- st_bbox(bound %>% filter(NHD_NUM %in% neighborhood))

for (i in neighborhood) {
  #create neighborhood data
  temp_df <- filter(base, nbhd_num == i)
  nbhd <- unique(temp_df$nbhd_name)
  
bound%>%
tm_shape(bbox = bb) + 
  tm_fill(col = "grey") + 
  tm_polygons()+
  bound%>%
  filter(., NHD_NUM == i)%>%
  tm_shape()+
  tm_fill(col = "forestgreen")+
  tm_credits("Source: City of St. Louis", position = c("left", "BOTTOM"), size = .5)+
  tm_layout(frame = FALSE) -> map

bound%>%
tm_shape()+
  tm_fill(col = "grey")+
  tm_borders(col = "white")+
  bound%>%
  filter(., NHD_NUM == i)%>%
  tm_shape()+
  tm_fill(col = "forestgreen")+
  tm_borders(col = "white")-> inset
  
tmap_save(map, insets_tm = inset, insets_vp = viewport(0.8, 0.75, width = 0.4, height = 0.4), file = here::here("NIBRS", "data", "neighborhoods", paste(nbhd, ".jpeg", sep = "")), width = 9, height = 5, units = "in")  

#create powerpoint slide
report%>%
add_slide()%>%
  ph_with(external_img(here::here("NIBRS", "data", "neighborhoods", paste(nbhd, ".jpeg", sep = "")), height = 5, width = 9), location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with(nbhd, 
               location = ph_location_type(
                 type = "title") )-> report

  
  #reference column name using params$month1
tc <- sum(temp_df[grep(params$month1, colnames(temp_df))])
persons <- filter(temp_df, type == "Person")
persons <- sum(persons[grep(params$month1, colnames(temp_df))])
society <- filter(temp_df, type == "Society")
society <- sum(society[grep(params$month1, colnames(temp_df))])
property <- filter(temp_df, type == "Property")
property <- sum(property[grep(params$month1, colnames(temp_df))])
unspec <- filter(temp_df, type == "Unspecified")
unspec <- sum(unspec[grep(params$month1, colnames(temp_df))])


sprint_1 <- sprintf("%s total crimes in %s %s", 
                    tc, params$month, params$year)

# create summary notes
summary <- block_list(
  fpar(ftext(sprint_1, boldline)),
  fpar(ftext(persons, bold),
       (ftext(" crime(s) against persons", reg24))),
  fpar(ftext(property, bold),
       ftext(" crime(s) against property", reg24)),
  fpar(ftext(society, bold),
       ftext(" crime(s) against society", reg24)),
  fpar(ftext(unspec, bold),
       ftext(" unspecified crimes", reg24))
  )

# write summary notes to powerpoint slide
report%>%
  add_slide(layout = 'Title and Content', master = 'Office Theme')%>%
  ph_with(value = paste(nbhd, ": Summary Notes"), location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE, level_list = c(1, 2, 2, 2, 2)) -> report
###
###Must Change summarise every time you run code!
###
overview <- temp_df%>%
  dplyr::group_by(type)%>%
  dplyr::summarise(Jan = sum(Jan), Feb = sum(Feb), Mar = sum(Mar))%>%
  adorn_totals("row", name = "Total")%>%
  dplyr::rename("Type of Crime" = type)
###  
###
###
#Make flextables from summary data
flextable(overview) %>%
  height_all(.25, part = "all")%>%
  width(j = "Type of Crime", width = 1)-> flex

#Month by Month total crime plot
plot_df <- temp_df%>%
  summarise(Jan = sum(Jan), Feb = sum(Feb), Mar = sum(Mar))
#reshape data
plot_df <- melt(plot_df)

ggplot(plot_df, aes(x=variable, y=value, group = 1)) +
    geom_line(color="blue") +
    geom_point() +
    xlab("Month") + ylab("Total Crimes")

ggsave(here::here("NIBRS", "results",  params$year, params$month, paste(nbhd, "_graph.jpeg", sep = "")), width = 5, height = 5.45, units = "in")

report%>%
add_slide()%>%
  ph_with(external_img(here::here("NIBRS", "results", params$year, params$month, paste(nbhd, "_graph.jpeg", sep = "")), height = 5.45, width = 5), location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  phl_with_flextable(olay = offlayout, 4, flex)%>%
  ph_with(nbhd, 
               location = ph_location_type(
                 type = "title") )-> report 

for (x in type) {
  sub <- temp_df%>%
    filter(type == x)%>%
    subset(select=-c(nbhd_num,nbhd_name,type))%>%
    adorn_totals(., "col", name = "Total")
  
  if(x != "Property"){
    sub <- adorn_totals(sub, "row", name = "Total")
    head <- head(sub, 21)
  }else{
    head <- head(sub, 20)
  }
  
 flextable(head)%>%
  height_all(.25, part = "all")%>%
  width(width = 3, j = "Crime")->ft 
  
  report%>%
  add_slide()%>%
  ph_with(ft, location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  phl_with_text(olay = offlayout01, 1, paste(nbhd, ":", x, "Crimes"), type = "title") ->report
  
if(x == "Property"){
  #add row totals from ft & ft2
  tail <- adorn_totals(sub, "row", name = "Total")
  #select observations after first 20
  tail <- tail(tail, -20)
  flextable(tail)%>%
    height_all(.25, part = "all")%>%
    width(width = 3, j = "Crime") -> ft2

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(ft2, location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  phl_with_text(olay = offlayout01, 1, paste(nbhd, ":", x, "Crimes"), type = "title")-> report
}
}
}
print(report, target = here::here("NIBRS", "results", "test.pptx"))
```

###Inset Map
```{r, eval = FALSE}
library(sf)
library(gateway)


nbhds <- sort(unique(data_sf$nbhd_name))
for (i in neighborhood) {

  #new tmap with bbox
bound%>%
tm_shape(bbox = bb) + 
  tm_fill(col = "grey") + 
  tm_polygons()+
  bound%>%
  filter(., NHD_NUM == i)%>%
  tm_shape()+
  tm_fill(col = "forestgreen")+
  tm_credits("Source: City of St. Louis", position = c("left", "BOTTOM"), size = .5)+
  tm_layout(frame = FALSE)-> map
  


bound%>%
tm_shape()+
  tm_fill(col = "grey")+
  tm_borders(col = "white")+
  bound%>%
  filter(., NHD_NUM == i)%>%
  tm_shape()+
  tm_fill(col = "forestgreen")+
  tm_borders(col = "white")-> inset
  
tmap_save(map, insets_tm = inset, insets_vp = viewport(0.8, 0.75, width = 0.4, height = 0.4), file = here::here("NIBRS", "data", params$year, "test.jpeg"), width = 9, height = 5, units = "in")
  
}
```

